name: Deploy

on:
  push:
    branches: [ feature/**, release/**, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "Build" ]
    types: [ completed ]
    branches: [ feature/**, release/**, main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # 배포는 추후 작성
    steps:
      # 현재 레포지토리 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # 정상적으로 clone 되었는지 확인
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al

      # JAVA JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      # application-dev.yml 파일 생성
      - name: Set application-dev.yml
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.APPLICATION_DEV }}" > ./application-dev.yml
          ls -al

      # application.yml 파일 생성 staging 배포
      # release 브랜치일 경우 staging 배포
      - name: Set application-dev.yml
        if: ${{ conatains(github.ref_name, 'feature/') }}
        run: |
          touch ./application.yml
          echo "${{ secrets.APPLICATION_STAGING }}" > ./application.yml
          ls -al

      # application.yml 파일 생성 production 배포
      # main 브랜치일 경우 production 배포
      - name: Set application-dev.yml
        if: ${{ github.ref_name == 'main' }}
        run: |
          touch ./application.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application.yml
          ls -al

      # meta
      # application.yml 파일 생성 staging 배포
      # release 브랜치일 경우 staging 배포
      - name: Set application.yml
        if: ${{ steps.meta.outputs.labels == 'feature/**' }}
        run: |
          touch ./application.yml
          echo "${{ secrets.APPLICATION_STAGING }}" > ./application.yml
          ls -al

      # meta
      # application.yml 파일 생성 production 배포
      # main 브랜치일 경우 production 배포
      - name: Set application.yml
        if: ${{ steps.meta.outputs.labels == 'main' }}
        run: |
          touch ./application.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application.yml
          ls -al

      # Spring 빌드
      - name: Spring Build, Make .jar
        run:
          ./gradlew build

      # Docker 설정
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2

      # Docker 빌드
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Image meta 설정
      - name: Set up Docker Image meta data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: comstering/baesa

      # Docker Hub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Build, Docker Hub Push
      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
