name: Test
on:
  workflow_dispatch:

jobs:
  job1:
    uses: jinsuseoungchan/.github/.github/workflow-templates/octo-organization-ci.yaml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "success"
